// <auto-generated />
using System;
using CMS.Infra.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMS.Infra.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190118134855_Migration_0")]
    partial class Migration_0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMS.Dominio.Entidades.AreaWebsite", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("IdHtml");

                    b.Property<Guid>("IdWebsite");

                    b.Property<string>("Nome");

                    b.HasKey("ID");

                    b.HasIndex("IdWebsite");

                    b.ToTable("AreaWebsite");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.CMSFaleConosco", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<bool>("HabilitarEmail");

                    b.Property<bool>("HabilitarLocalizacao");

                    b.Property<bool>("HabilitarWhatsApp");

                    b.Property<string>("Localizacao");

                    b.HasKey("ID");

                    b.ToTable("CMSFaleConosco");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.CMSParceiros", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Titulo");

                    b.HasKey("ID");

                    b.ToTable("CMSParceiros");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.CMSPlanos", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SubTitulo");

                    b.Property<string>("Titulo");

                    b.HasKey("ID");

                    b.ToTable("CMSPlanos");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.CMSServicos", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Conteudo");

                    b.Property<bool>("HabilitarImagem");

                    b.Property<bool>("HabilitarTitulo");

                    b.Property<byte[]>("Imagem");

                    b.Property<byte[]>("ImagemCitacao");

                    b.Property<string>("ImagemCitacaoType");

                    b.Property<string>("ImagemType");

                    b.Property<bool>("SubTitulo");

                    b.Property<string>("SubtTitulo");

                    b.Property<string>("TextoCitacao");

                    b.Property<string>("Titulo");

                    b.HasKey("ID");

                    b.ToTable("CMSServicos");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.CMSSobre", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Conteudo");

                    b.Property<bool>("HabilitarFacebook");

                    b.Property<bool>("HabilitarGoogleMais");

                    b.Property<bool>("HabilitarImagem");

                    b.Property<bool>("HabilitarInstagram");

                    b.Property<bool>("HabilitarPinterest");

                    b.Property<bool>("HabilitarTitulo");

                    b.Property<bool>("HabilitarWhatsApp");

                    b.Property<byte[]>("Imagem");

                    b.Property<string>("ImagemType");

                    b.Property<bool>("SubTitulo");

                    b.Property<string>("SubtTitulo");

                    b.Property<string>("Titulo");

                    b.HasKey("ID");

                    b.ToTable("CMSSobre");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.CMSTabelaDePlanos", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descircao");

                    b.Property<Guid>("IdCMSPlanos");

                    b.Property<string>("TextoFooter");

                    b.Property<string>("TextoHeader");

                    b.Property<decimal>("ValorPlano");

                    b.HasKey("ID");

                    b.HasIndex("IdCMSPlanos");

                    b.ToTable("CMSTabelaDePlanos");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.CMShome", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("HabilitarFacebook");

                    b.Property<bool>("HabilitarGoogleMais");

                    b.Property<bool>("HabilitarInstagram");

                    b.Property<bool>("HabilitarPinterest");

                    b.Property<bool>("HabilitarTwitter");

                    b.Property<bool>("HabilitarWhatsApp");

                    b.Property<byte[]>("SlideImagem");

                    b.Property<string>("SlideImagemType");

                    b.Property<string>("SubTitulo");

                    b.Property<string>("Titulo");

                    b.HasKey("ID");

                    b.ToTable("CMSHome");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.CardParceiros", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("FacebookURL");

                    b.Property<string>("GoogleMaisURL");

                    b.Property<bool>("HabilitarFacebook");

                    b.Property<bool>("HabilitarGoogleMais");

                    b.Property<bool>("HabilitarInstagram");

                    b.Property<bool>("HabilitarPinterest");

                    b.Property<bool>("HabilitarWhatsApp");

                    b.Property<string>("InstagramURL");

                    b.Property<byte[]>("LogoParceiro");

                    b.Property<string>("LogoParceiroType");

                    b.Property<string>("NomeParceiro");

                    b.Property<string>("PinterestURL");

                    b.Property<string>("TwitterURL");

                    b.Property<string>("WhatsAppNumero");

                    b.HasKey("ID");

                    b.ToTable("CardParceiros");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.ImagemGaleria", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Imagem");

                    b.Property<string>("ImagemType");

                    b.HasKey("ID");

                    b.ToTable("ImagemGaleria");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.Website", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CMSFaleConoscoID");

                    b.Property<Guid?>("CMSParceirosID");

                    b.Property<Guid?>("CMSPlanosID");

                    b.Property<Guid?>("CMSServicosID");

                    b.Property<Guid?>("CMShomeID");

                    b.Property<string>("FacebookURL");

                    b.Property<string>("GoogleMaisURL");

                    b.Property<byte[]>("Icone");

                    b.Property<string>("IconeType");

                    b.Property<Guid>("IdCMSFaleConosco");

                    b.Property<Guid>("IdCMSGaleriaFotos");

                    b.Property<Guid>("IdCMSHome");

                    b.Property<Guid>("IdCMSParceiros");

                    b.Property<Guid>("IdCMSPlanos");

                    b.Property<Guid>("IdCMSServiso");

                    b.Property<string>("InstagramURL");

                    b.Property<byte[]>("LogoTopo");

                    b.Property<string>("LogoTopoType");

                    b.Property<string>("NomeWebsite");

                    b.Property<string>("PinterestURL");

                    b.Property<string>("TituloHeader");

                    b.Property<string>("TwitterURL");

                    b.Property<string>("WhatsAppNumero");

                    b.HasKey("ID");

                    b.HasIndex("CMSFaleConoscoID");

                    b.HasIndex("CMSParceirosID");

                    b.HasIndex("CMSPlanosID");

                    b.HasIndex("CMSServicosID");

                    b.HasIndex("CMShomeID");

                    b.ToTable("Website");
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.AreaWebsite", b =>
                {
                    b.HasOne("CMS.Dominio.Entidades.Website", "Website")
                        .WithMany("AreaWebsites")
                        .HasForeignKey("IdWebsite")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.CMSTabelaDePlanos", b =>
                {
                    b.HasOne("CMS.Dominio.Entidades.CMSPlanos", "CMSPlanos")
                        .WithMany("cMSTabelaDePlanos")
                        .HasForeignKey("IdCMSPlanos")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CMS.Dominio.Entidades.Website", b =>
                {
                    b.HasOne("CMS.Dominio.Entidades.CMSFaleConosco", "CMSFaleConosco")
                        .WithMany()
                        .HasForeignKey("CMSFaleConoscoID");

                    b.HasOne("CMS.Dominio.Entidades.CMSParceiros", "CMSParceiros")
                        .WithMany()
                        .HasForeignKey("CMSParceirosID");

                    b.HasOne("CMS.Dominio.Entidades.CMSPlanos", "CMSPlanos")
                        .WithMany()
                        .HasForeignKey("CMSPlanosID");

                    b.HasOne("CMS.Dominio.Entidades.CMSServicos", "CMSServicos")
                        .WithMany()
                        .HasForeignKey("CMSServicosID");

                    b.HasOne("CMS.Dominio.Entidades.CMShome", "CMShome")
                        .WithMany()
                        .HasForeignKey("CMShomeID");
                });
#pragma warning restore 612, 618
        }
    }
}
